#!/bin/bash
version=`python3 -c "import electrum_redd; print(electrum_redd.version.ELECTRUM_VERSION)"`
sig=`./run_electrum -o signmessage $SIGNING_ADDRESS $version -w $SIGNING_WALLET`
echo "{\"electrum\":{\"version\":\"$version\", \"signatures\":{ \"$SIGNING_ADDRESS\":\"$sig\"}}}"
