# This file lists translatable strings used in the Android app which don't appear anywhere else
# in the Electron Cash repository. Some of them only differ in capitalization or punctuation:
# see https://medium.com/@jsaito/making-a-case-for-letter-case-19d09f653c98
#
# If you change this file, you'll need to rebuild the strings.xml files by following the
# instructions in android/README.md.
#
# Please keep the strings in alphabetical order.


def _(s):
    return s

_("%1$s bytes")
_("%s copied to clipboard")
_("%1$s sat/byte")
_("A wallet with that name already exists, please try again.")
_("Appearance")
_("Are you sure you want to delete your wallet \'%s\'?")
_("Are you sure you wish to delete this contact?")
_("Are you sure you wish to proceed?")
_("BIP39 seed")
_("Block explorer")
_("Cannot specify private keys and addresses in the same wallet.")
_("CashAddr address format")
_("Change password")
_("Close wallet")
_("Confirm Delete")
_("Confirm password")
_("Connected to %d nodes.")
_("Console")
_("Contact")
_("Copyright © 2017-2020 Electron Cash LLC and the Electron Cash developers.")
_("Create")
_("Create a new seed")
_("Current password")
_("delete")
_("Delete")
_("Delete wallet")
_("Delete Wallet")
_("derivation")
_("Derivation invalid")
_("Derivation Invalid")
_("Disconnect")
_("Electron Cash is generating your addresses, please wait.")
_("Electron Cash is generating your addresses, please wait...")
_('Enter a filename for the copy of your wallet')
_("Enter a list of Bitcoin Cash addresses (this will create a watching-only wallet), or a list of private keys.")
_("Enter password")
_("Export wallet")
_("Filenames cannot contain the '/' character. Please enter a different filename to proceed.")
_("For support, please visit us on <a href='https://github.com/Electron-Cash/Electron-Cash/issues'>"
  "GitHub</a> or on <a href='https://t.me/electroncashwallet'>Telegram</a>.")
_("ID")
_("If you are not sure what this is, leave this field unchanged.")
_("If your wallet contains funds, make sure you have saved its seed.")
_("Import addresses")
_("Import addresses or private keys")
_("Import Addresses or Private Keys")
_("Invalid address")
_("Load transaction")
_("Made with <a href='https://chaquo.com/chaquopy'>Chaquopy</a>, the Python SDK for Android.")
_("Name is empty")
_("New password")
_("New wallet")
_("New Wallet")
_("No wallet")
_("No Wallet is open.")
_("No Wallet Is Open")
_("Not a valid address or private key: '%s'")
_("Online")
_("Passphrase")
_("Please specify a master key to continue. Valid keys are long strings starting with either xpub/ypub/zpub or xprv/yprv/zprv.")
_("Press the menu button above to open or create one.")
_("QR code")
_("Rename wallet")
_("Rename Wallet")
_("Request")
_("Request URI")
_("Restore from seed")
_("Restore from Seed")
_("Show seed")
_("Sign transaction")
_("Size")
_("Signed transaction")
_("Text copied to clipboard")
_("The seed you entered does not appear to be a valid wallet seed.")
_("The string you entered has been broadcast. Please check your transactions for confirmation.")
_("Transaction not found")
_("Transaction Not Found")
_("Type, paste, or scan a valid signed transaction in hex format below:")
_("Use a master key")
_("Use a Master Key")
_("Verifying {count} block please wait ...")
_("Verify {count} Cash Account")
_("Wallet name")
_("Wallet name is too long")
_("Wallet names cannot contain the '/' character. Please enter a different wallet name to proceed.")
_("Wallet exported successfully")
_("Wallet passwords do not match. Please confirm the password you wish to set for your wallet by entering the same password twice.")
_("Wallet renamed successfully")
_("Wallet seed")
_("Wallet Seed")
_("You appear to have entered no valid Bitcoin Cash addresses or private keys.")
_("You don't have any contacts.")
